export const NODES_JOB_NAMES = {
    START_NODE: 'startNode',
    STOP_NODE: 'stopNode',
    NODE_HEALTH_CHECK: 'nodeHealthCheck',
    ADD_USER_TO_NODE: 'addUserToNode',
    ADD_USERS_TO_NODE: 'addUsersToNode',
    REMOVE_USERS_FROM_NODE: 'removeUsersFromNode',
    REMOVE_USER_FROM_NODE: 'removeUserFromNode',
    START_ALL_BY_PROFILE: 'startAllByProfile',
    START_ALL_NODES: 'startAllNodes',
    RECORD_USER_USAGE: 'recordUserUsage',
    RECORD_NODE_USAGE: 'recordNodeUsage',
    FETCH_IPS_LIST: 'fetchIpsList',
    FETCH_USERS_IPS_LIST: 'fetchUsersIpsList',
    DROP_USERS_CONNECTIONS: 'dropUsersConnections',
    DROP_IPS_CONNECTIONS: 'dropIpsConnections',
    SYNC_NODE_PLUGINS: 'syncNodePlugins',
    COLLECT_REPORTS: 'collectReports',

    BLOCK_IPS: 'blockIps',
    UNBLOCK_IPS: 'unblockIps',
    RECREATE_TABLES: 'recreateTables',
} as const;
