export const QUEUES_NAMES = {
    NODES: {
        HEALTH_CHECK: 'NODES_HEALTH_CHECK_QUEUE',
        START: 'NODES_START_NODE_QUEUE',
        STOP: 'NODES_STOP_NODE_QUEUE',
        USERS: 'NODES_NODE_USERS_QUEUE',
        BULK_USERS: 'NODES_BULK_USERS_QUEUE',
        START_ALL_BY_PROFILE: 'NODES_START_ALL_BY_PROFILE_QUEUE',
        START_ALL_NODES: 'NODES_START_ALL_NODES_QUEUE',
        RECORD_USER_USAGE: 'NODES_RECORD_USER_USAGE_QUEUE',
        RECORD_NODE_USAGE: 'NODES_RECORD_NODE_USAGE_QUEUE',
        QUERY_NODES: 'NODES_QUERY_NODES_QUEUE',
        PLUGINS: 'NODES_PLUGINS_QUEUE',
    },
    SQUADS: {
        ACTIONS: 'SQUADS_ACTIONS_QUEUE',
    },
    USERS: {
        SERIAL_OPERATIONS: 'USERS_SERIAL_OPERATIONS_QUEUE',
        MODIFY_MANY: 'USERS_MODIFY_MANY_QUEUE',
        SUBSCRIPTION_REQUESTS: 'USERS_SUBSCRIPTION_REQUESTS_QUEUE',
        RESET_USER_TRAFFIC: 'USERS_RESET_USER_TRAFFIC_QUEUE',
        USERS_WATCHDOG: 'USERS_WATCHDOG_QUEUE',
        USER_EVENTS: 'USER_EVENTS_QUEUE',
        UPDATE_USERS_USAGE: 'USERS_UPDATE_USERS_USAGE_QUEUE',
    },
    NOTIFICATIONS: {
        TELEGRAM: 'NTFY_TELEGRAM_QUEUE',
        WEBHOOK: 'NTFY_WEBHOOK_QUEUE',
    },
    PUSH_TO_DB: 'PUSH_TO_DB_QUEUE',
    SERVICE: 'SERVICE_QUEUE',
} as const;
